baseURL = 'https://xinru-hao.github.io/'
languageCode = 'en-us'
title = "Xinru's Blog"
theme = 'PaperMod'

enableInlineShortcodes = true
enableEmoji = true
enableRobotsTXT = true
hasCJKLanguage = true
buildDrafts = false
buildFuture = false
buildExpired = false
paginate = 15
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

[params]
    auhtor = "Xinru Hao"
env = "production"
author = "Sulv"
defaultTheme = "auto"
disableThemeToggle = false
DateFormat = "2006-01-02"
ShowShareButtons = true
ShowReadingTime = true
displayFullLangName = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
hideFooter = false
ShowWordCounts = true
VisitCount = true
ShowLastMod = true
ShowToc = true
TocOpen = true
comments = true

  [[params.socialIcons]]
  name = "LinkedIn"
  url = "https://www.linkedin.com/in/xinru-hao-016a43227/"

  [[params.socialIcons]]
  name = "Email"
  url = "mailto:xinruhao7@gmail.com"




[menus]
[[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10
[[menus.main]]
    name = 'About me'
    pageRef = '/products'
    weight = 20
[[menus.main]]
    name = 'Project'
    pageRef = '/services'
    weight = 30
[[menus.main]]
    name = 'Resume'
    url = "/resumepdf/Resume1.pdf"
    weight = 40
[[menus.main]]
    name = 'Contact'
    pageRef = '/services'
    weight = 50


[languages.en]
languageName = "English"
weight = 1

  [languages.en.profileMode]
  enabled = true
  title = "Hi, I'm Xinru (〃'▽'〃)"
  imageUrl = "/images/avatar.jpg"
  imageWidth = 150
  imageHeight = 150

    [[languages.en.profileMode.buttons]]
    name = "🎓Education"
    url = "posts/tech"

    [[languages.en.profileMode.buttons]]
    name = "💼Professional Experience"
    url = "posts/read"

    [[languages.en.profileMode.buttons]]
    name = "💡Skills"
    url = "posts/read"

    [[languages.en.profileMode.buttons]]
    name = "🏖Life"
    url = "posts/life"

[label]
text = "Xinru's Blog"
icon = "images/avatar.jpg"
iconHeight = 35

[outputs]
home = [ "HTML", "RSS", "JSON" ]


[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
codeFences = true
guessSyntax = true
lineNos = true
style = "darcula"