baseURL = 'https://xinru-hao.github.io/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'anatole'
[params]
title = "I'm Xinru Hao"
author = "Xinru Hao"
description = "Call me Rosa"
profilePicture = "/images/avatar.jpg"
[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:xinruhao7@gmail.com"

[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/xinru-hao-016a43227/"

[menu]

  [[menu.main]]
  name = "About"
  identifier = "About"
  weight = 100
  url = "/aboutme/"

  [[menu.main]]
  name = "Project"
  weight = 200
  identifier = "Project"
  url = "/post/"

  [[menu.main]]
  name = "Resume"
  weight = 300
  identifier = "Resume"
  url = "/Resume/"