baseURL = 'https://xinru-hao.github.io/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'anatole'
[params]
title = "I'm Xinru Hao"
author = "Xinru Hao"
description = "Call me Rosa"
profilePicture = "/images/avatar.jpg"
